### PR TITLE
Redraw objects at next start rather than stop

### PR DESCRIPTION
**Pull request by charleshong3**
Also clean up some code from the last set of PRs.

Feel free to squash and merge on approval.

### CODE REVIEW

**Review by kevinzhu00 — COMMENTED** [review]
Do you want this functionality to persist in Teleop? It seems odd to have your objects to be delayed in uploading during autonomous but not during Teleop

**Comment by charleshong3** [comment]
Regardless of this PR, teleop and autonomous have different functionality because teleop updates immediately when "Upload Field" is pressed, in this code and the code on master. Autonomous always requires the simulation to end before the field is updated. This PR doesn't make any functionality worse/less consistent as far as I'm aware.

**Comment by charleshong3** [comment]
We could make it so that the field doesn't update in the middle of teleop simulations, but that would be a separate issue.

**Review by kevinzhu00 — CHANGES_REQUESTED** [review]
Currently the console prints "Field will update when autonomous simulation ends". However, since we are updating the field at the start of the next call we should update this as well.

**Review by kevinzhu00 — APPROVED** [review]
Looks Good

**Pull request merged**
