### PR TITLE
Selected buttons change colors

### LINKED ISSUE #99: [UI/UX] Dark mode removes button selection indication
For the Keyboard/Gamepad and Swift/Spry/Sturdy robots, there is a bug where you can’t tell which button is selected when dark mode is active.

### PR DESCRIPTION
**Pull request by nia-n**
Bug fix for some buttons (mostly robot type) that didn't change color or changed the wrong button's color when selected

### CODE REVIEW

**Comment by charleshong3** [comment]
The "run teleop" and "run autonomous" buttons don't change color when teleop/autonomous simulations are active in dark mode.

**Review by charleshong3 — CHANGES_REQUESTED** [review]
The "run teleop" and "run autonomous" buttons don't change color when teleop/autonomous simulations are active in dark mode.

**Comment by kevinzhu00** [comment]
Probably should change all the button colors in dark-mode.js. Right now it is manually changed in base.js. However, the bug Charles mentioned should be fixed

**Comment by charleshong3** [comment]
Nice, it does appear to work. Just need to fix merge conflict

**Review by charleshong3 — DISMISSED** [review]
lotm

**Review by charleshong3 — APPROVED** [review]
still looks ok

**Pull request merged**
